apiVersion: v1
kind: Pod
metadata:
  name: web-server
  labels:
    app: nginx  
spec:
  containers:
  - image: nginx
    name: web-container
    ports:
    - containerPort: 80
      protocol: TCP      
    volumeMounts:
    - name: nfs-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: nfs-volume
    persistentVolumeClaim:
      claimName: pvc-one
