apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvvol-1
spec:
  capacity:
    storage: 1Gi
  # volumeMode: Filesystem    
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  # storageClassName: slow
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  nfs:
    path: /opt/sfw
    server: k8scp
    readOnly: false
